name: football_predictor_flutter
description: "A Flutter project for predicting football matches."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  logger: ^2.0.2
  package_info_plus: ^6.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.1.11
  flutter_custom_tabs: ^2.0.0+1
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  flutter_web_auth_2: ^3.1.1
  local_auth: ^2.1.6
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_flavorizr: ^2.2.1

flutter:
  uses-material-design: true

  assets:
    - firebase/dev/
    - firebase/qa/
    - firebase/prod/

fonts:
  - family: Nunito
    fonts:
      - asset: fonts/Nunito-Regular.ttf
        weight: 400
      - asset: fonts/Nunito-Italic.ttf
        style: italic
        weight: 400
      - asset: fonts/Nunito-Bold.ttf
        weight: 700
      - asset: fonts/Nunito-BoldItalic.ttf
        style: italic
        weight: 700
      - asset: fonts/Nunito-ExtraBold.ttf
        weight: 800
      - asset: fonts/Nunito-ExtraBoldItalic.ttf
        style: italic
        weight: 800
      - asset: fonts/Nunito-ExtraLight.ttf
        weight: 200
      - asset: fonts/Nunito-ExtraLightItalic.ttf
        style: italic
        weight: 200
      - asset: fonts/Nunito-Light.ttf
        weight: 300
      - asset: fonts/Nunito-LightItalic.ttf
        style: italic
        weight: 300
      - asset: fonts/Nunito-Medium.ttf
        weight: 500
      - asset: fonts/Nunito-MediumItalic.ttf
        style: italic
        weight: 500
      - asset: fonts/Nunito-SemiBold.ttf
        weight: 600
      - asset: fonts/Nunito-SemiBoldItalic.ttf
        style: italic
        weight: 600
      - asset: fonts/Nunito-Black.ttf
        weight: 900
      - asset: fonts/Nunito-BlackItalic.ttf
        style: italic
        weight: 900

# The following section is specific to build flavors.
flavorizr:
  ide: "idea"
  flavors:
    prod:
      app:
        name: "FP_PROD"
      android:
        applicationId: "com.football.predictor.prod"
        firebase:
          config: "firebase/prod/google-services.json"
      ios:
        bundleId: "com.football.predictor.prod"
        firebase:
          config: "firebase/prod/GoogleService-Info.plist"
    qa:
      app:
        name: "FP_QA"
      android:
        applicationId: "com.football.predictor.qa"
        firebase:
          config: "firebase/qa/google-services.json"
      ios:
        bundleId: "com.football.predictor.qa"
        firebase:
          config: "firebase/qa/GoogleService-Info.plist"
    dev:
      app:
        name: "FP_DEV"
      android:
        applicationId: "com.football.predictor.dev"
        firebase:
          config: "firebase/dev/google-services.json"
      ios:
        bundleId: "com.football.predictor.dev"
        firebase:
          config: "firebase/dev/GoogleService-Info.plist"

